### ISSUE TITLE
Space is being included in alternation

### ISSUE THREAD

**Issue by thewetzel** [martinthomson/abnf2regex#1]
The following was produced by abnf2regex:
FULL = (MONTH SP DAY)
 ; Expanded: FULL = (("Jan" / "Feb" / %x20) (2%x30-39 / (%x20 %x30-39)))
 ; Regex: (?: |[Jj][Aa][Nn]|[Ff][Ee][Bb])(?:\d{2}| \d)
MONTH = ("Jan" / "Feb")
 ; Expanded: MONTH = ("Jan" / "Feb")
 ; Regex: (?:[Jj][Aa][Nn]|[Ff][Ee][Bb])
DAY = (2DIGIT / (SP DIGIT))
 ; Expanded: DAY = (2%x30-39 / (%x20 %x30-39))
 ; Regex: (?:\d{2}| \d)

Notice that the SP is being lumped in with the MONTH alternation rule, so it won't match "Jan 25" for example, but it will match "Jan25".

Any help would be appreciated. Thanks.

**Comment by martinthomson** [comment]
This is clearly a bug.  I might get to this, but it's been a while since I've written some java, so my development environment needs setting up.

The code that you might want to poke at is here:
https://github.com/martinthomson/abnf2regex/blob/master/abnf2regex/src/net/abnf2regex/GroupFragment.java#L91

It's pretty obtuse code (sorry), but it's probably a false positive in canCollapse().  I'll see what I can work out when I get some free time.

**Comment by martinthomson** [comment]
Let me know if the latest fix works for you.  I think that it should.
